disabled_rules:
- opening_brace
- large_tuple
- file_length
- type_body_length

line_length:
  warning: 160
  ignores_function_declarations: true
  ignores_comments: true
  ignores_interpolated_strings: true
  ignores_urls: true

file_length: 400

type_body_length: 250

function_body_length: 50
